export const ROUTES = {
	login: '/auth/login',
	register: '/auth/register',
	refresh: '/auth/refresh',
	logout: '/auth/logout',
	userNeighborhoods: '/neighborhood/user_neighborhoods',
	currentNeighborhood: '/neighborhood',
	debts: '/debt/debts',
	debtors: '/debt/debtors',
	closeDebt: '/debt/close_debt',
	deleteDebt: '/debt/delete_debt',
	reopenDebt: '/debt/reopen_debt',
	partialPayment: '/debt/partial_payment',
	reduceDebt: '/debt/reduce_debt',
	increaseDebt: '/debt/increase_debt',
	editDebt: '/debt/edit_debt',
	debtHistory: '/debt/history',
	createDebt: 'debt/create_debt',
};
